apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: demo
  namespace: otel
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      datadog:
        api:
          site: datadoghq.com
          key: ${env:DD_API_KEY}

    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [datadog]
        metrics:
          receivers: [otlp]
          exporters: [datadog]
        traces:
          receivers: [otlp]
          exporters: [datadog]
  env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          key:  api-key
          name: dd-api-key