apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-auth-app
  namespace: otel
  labels:
    app: datadog-auth-app
    tags.datadoghq.com/env: production
    tags.datadoghq.com/service: datadog-auth-app
    tags.datadoghq.com/version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-auth-app
  template:
    metadata:
      labels:
        app: datadog-auth-app
        tags.datadoghq.com/env: production
        tags.datadoghq.com/service: datadog-auth-app
        tags.datadoghq.com/version: v1.0
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - name: datadog-auth-app
        image: uehara96/otel:auth-v1
        ports:
        - containerPort: 8082
        imagePullPolicy: Always
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: datadog-auth-app-svc
  namespace: otel
spec:
  type: NodePort
  selector:
    app: datadog-auth-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8082
      targetPort: 8082
